// packages/ui/src/components/OverlayEditor.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import type { Overlay, ArrowDirection } from '@guidenav/types';
import OverlayCanvas from './OverlayCanvas.vue';
import OverlayToolbar from './OverlayToolbar.vue';
import LabelInputModal from './LabelInputModal.vue';
import OverlayTutorial from './OverlayTutorial.vue';
import { useOverlayTutorials, useIsMobile, type OverlayTutorialType } from '../composables/useTutorialState';

type EditorMode = 'view' | 'add-arrow' | 'add-marker' | 'select';

interface Props {
  imageUrl: string;
  overlays: Overlay[];
  readonly?: boolean;
  userId?: string;
}

const props = withDefaults(defineProps<Props>(), {
  readonly: false,
  userId: 'dev-user-placeholder',
});

const emit = defineEmits<{
  'update:overlays': [overlays: Overlay[]];
}>();

const mode = ref<EditorMode>('view');
const selectedOverlayId = ref<string | null>(null);
const showLabelModal = ref(false);
const pendingMarkerPosition = ref<{ x: number; y: number } | null>(null);
const editingLabelOverlayId = ref<string | null>(null);

const { 
  hasSeenArrowTutorial, 
  hasSeenMarkerTutorial, 
  markArrowTutorialSeen, 
  markMarkerTutorialSeen 
} = useOverlayTutorials(props.userId);
const { isMobile } = useIsMobile();
const showTutorial = ref(false);
const tutorialType = ref<OverlayTutorialType>('arrow');

const showArrowTypePicker = ref(false);
const pendingArrowDirection = ref<ArrowDirection>('up-down');

const hasArrow = computed(() => props.overlays.some(o => o.type === 'arrow'));
const hasMarker = computed(() => props.overlays.some(o => o.type === 'marker'));

const selectedOverlay = computed(() => {
  if (!selectedOverlayId.value) return null;
  return props.overlays.find(o => o.id === selectedOverlayId.value) ?? null;
});

const labelModalTitle = computed(() => {
  if (editingLabelOverlayId.value) {
    const overlay = props.overlays.find(o => o.id === editingLabelOverlayId.value);
    return overlay?.label ? 'Edit Label' : 'Add Label';
  }
  return 'Add Label';
});

const labelModalInitialValue = computed(() => {
  if (editingLabelOverlayId.value) {
    const overlay = props.overlays.find(o => o.id === editingLabelOverlayId.value);
    return overlay?.label ?? '';
  }
  return '';
});

const arrowDirections: { value: ArrowDirection; label: string; icon: string }[] = [
  { value: 'left', label: 'Left', icon: '↰' },
  { value: 'right', label: 'Right', icon: '↱' },
  { value: 'up-down', label: 'Up/Down', icon: '↕' },
  { value: 'forward-backward', label: 'Forward/Back', icon: '⬆' },
];

function generateId(): string {
  return `overlay-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

function handleAddArrowClick() {
  if (props.readonly) return;
  
  if (mode.value === 'add-arrow') {
    mode.value = 'view';
    showArrowTypePicker.value = false;
    return;
  }
  
  showArrowTypePicker.value = true;
  selectedOverlayId.value = null;
}

function handleArrowTypeSelect(direction: ArrowDirection) {
  pendingArrowDirection.value = direction;
  showArrowTypePicker.value = false;
  mode.value = 'add-arrow';
}

function handleArrowTypePickerCancel() {
  showArrowTypePicker.value = false;
}

function handleAddMarkerClick() {
  if (props.readonly) return;
  
  mode.value = mode.value === 'add-marker' ? 'view' : 'add-marker';
  selectedOverlayId.value = null;
}

function handleTutorialComplete() {
  if (tutorialType.value === 'arrow') {
    markArrowTutorialSeen();
  } else {
    markMarkerTutorialSeen();
  }
  showTutorial.value = false;
}

function handleTutorialSkip() {
  if (tutorialType.value === 'arrow') {
    markArrowTutorialSeen();
  } else {
    markMarkerTutorialSeen();
  }
  showTutorial.value = false;
}

function handleSelectOverlay(id: string | null) {
  selectedOverlayId.value = id;
  if (id) {
    mode.value = 'select';
  } else if (mode.value === 'select') {
    mode.value = 'view';
  }
}

function handleAddOverlay(x: number, y: number) {
  if (mode.value === 'add-arrow') {
    const newOverlay: Overlay = {
      id: generateId(),
      type: 'arrow',
      x,
      y,
      scale: 2,
      rotation: 0,
      label: null,
      arrowDirection: pendingArrowDirection.value,
    };
    const filteredOverlays = props.overlays.filter(o => o.type !== 'arrow');
    emit('update:overlays', [...filteredOverlays, newOverlay]);
    selectedOverlayId.value = newOverlay.id;
    mode.value = 'select';
    
    if (isMobile.value && !hasSeenArrowTutorial.value) {
      tutorialType.value = 'arrow';
      showTutorial.value = true;
    }
  }
}

function handleCanvasTap(x: number, y: number) {
  if (mode.value === 'add-marker') {
    const newOverlay: Overlay = {
      id: generateId(),
      type: 'marker',
      x,
      y,
      scale: 1,
      rotation: 0,
      label: null,
    };
    const filteredOverlays = props.overlays.filter(o => o.type !== 'marker');
    emit('update:overlays', [...filteredOverlays, newOverlay]);
    selectedOverlayId.value = newOverlay.id;
    mode.value = 'select';
    
    if (isMobile.value && !hasSeenMarkerTutorial.value) {
      tutorialType.value = 'marker';
      showTutorial.value = true;
    }
  }
}

function handleLabelSave(label: string) {
  if (editingLabelOverlayId.value) {
    const updatedOverlays = props.overlays.map(o => 
      o.id === editingLabelOverlayId.value ? { ...o, label } : o
    );
    emit('update:overlays', updatedOverlays);
    editingLabelOverlayId.value = null;
  } else if (pendingMarkerPosition.value) {
    const newOverlay: Overlay = {
      id: generateId(),
      type: 'marker',
      x: pendingMarkerPosition.value.x,
      y: pendingMarkerPosition.value.y,
      scale: 1,
      rotation: 0,
      label,
    };
    const filteredOverlays = props.overlays.filter(o => o.type !== 'marker');
    emit('update:overlays', [...filteredOverlays, newOverlay]);
    selectedOverlayId.value = newOverlay.id;
    pendingMarkerPosition.value = null;
    mode.value = 'select';
  }
  showLabelModal.value = false;
}

function handleLabelCancel() {
  pendingMarkerPosition.value = null;
  editingLabelOverlayId.value = null;
  showLabelModal.value = false;
}

function handleUpdateOverlay(id: string, updates: Partial<Overlay>) {
  const updatedOverlays = props.overlays.map(o => 
    o.id === id ? { ...o, ...updates } : o
  );
  emit('update:overlays', updatedOverlays);
}

function handleChangeDirection(direction: ArrowDirection) {
  if (!selectedOverlayId.value) return;
  const overlay = props.overlays.find(o => o.id === selectedOverlayId.value);
  if (overlay && overlay.type === 'arrow') {
    handleUpdateOverlay(selectedOverlayId.value, { arrowDirection: direction });
  }
}

function handleEditLabel() {
  if (!selectedOverlayId.value) return;
  editingLabelOverlayId.value = selectedOverlayId.value;
  showLabelModal.value = true;
}

function handleDelete() {
  if (!selectedOverlayId.value) return;
  const updatedOverlays = props.overlays.filter(o => o.id !== selectedOverlayId.value);
  emit('update:overlays', updatedOverlays);
  selectedOverlayId.value = null;
  mode.value = 'view';
}

function handleDone() {
  selectedOverlayId.value = null;
  mode.value = 'view';
}

watch(() => props.readonly, (isReadonly) => {
  if (isReadonly) {
    mode.value = 'view';
    selectedOverlayId.value = null;
  }
});
</script>

<template>
  <div class="overlay-editor">
    <OverlayCanvas
      :image-url="imageUrl"
      :overlays="overlays"
      :selected-id="selectedOverlayId"
      :mode="mode"
      @select-overlay="handleSelectOverlay"
      @add-overlay="handleAddOverlay"
      @update-overlay="handleUpdateOverlay"
      @canvas-tap="handleCanvasTap"
    />
    
    <div v-if="!readonly" class="overlay-editor__controls">
      <div class="overlay-editor__add-buttons">
        <span class="overlay-editor__label">Overlay:</span>
        
        <div class="overlay-editor__arrow-btn-wrapper">
          <button
            class="overlay-editor__add-btn"
            :class="{ 'overlay-editor__add-btn--active': mode === 'add-arrow' || showArrowTypePicker }"
            @click="handleAddArrowClick"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M7 17L17 7M17 7H7M17 7V17" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            {{ hasArrow ? 'Replace Arrow' : 'Add Arrow' }}
          </button>
          
          <Transition name="arrow-picker">
            <div v-if="showArrowTypePicker" class="overlay-editor__arrow-picker">
              <div class="overlay-editor__arrow-picker-header">
                <span class="overlay-editor__arrow-picker-title">Choose arrow type</span>
                <button 
                  class="overlay-editor__arrow-picker-close"
                  @click="handleArrowTypePickerCancel"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg>
                </button>
              </div>
              <div class="overlay-editor__arrow-picker-grid">
                <button
                  v-for="dir in arrowDirections"
                  :key="dir.value"
                  class="overlay-editor__arrow-picker-option"
                  @click="handleArrowTypeSelect(dir.value)"
                >
                  <span class="overlay-editor__arrow-picker-icon">{{ dir.icon }}</span>
                  <span class="overlay-editor__arrow-picker-label">{{ dir.label }}</span>
                </button>
              </div>
            </div>
          </Transition>
        </div>
        
        <button
          class="overlay-editor__add-btn"
          :class="{ 'overlay-editor__add-btn--active': mode === 'add-marker' }"
          @click="handleAddMarkerClick"
        >
          <span class="overlay-editor__marker-dot" />
          {{ hasMarker ? 'Replace Marker' : 'Add Marker' }}
        </button>
      </div>
      
      <div v-if="selectedOverlay" class="overlay-editor__toolbar-container">
        <OverlayToolbar
          :overlay-type="selectedOverlay.type"
          :arrow-direction="selectedOverlay.arrowDirection"
          :has-label="!!selectedOverlay.label"
          :visible="true"
          @change-direction="handleChangeDirection"
          @edit-label="handleEditLabel"
          @delete="handleDelete"
          @done="handleDone"
        />
      </div>
    </div>
    
    <LabelInputModal
      :visible="showLabelModal"
      :initial-value="labelModalInitialValue"
      :title="labelModalTitle"
      @update:visible="showLabelModal = $event"
      @save="handleLabelSave"
      @cancel="handleLabelCancel"
    />
    
    <OverlayTutorial
      :visible="showTutorial"
      :type="tutorialType"
      @complete="handleTutorialComplete"
      @skip="handleTutorialSkip"
    />
  </div>
</template>

<style scoped>
.overlay-editor {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.overlay-editor__controls {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.overlay-editor__add-buttons {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}

.overlay-editor__label {
  font-size: 12px;
  color: #99a1af;
}

.overlay-editor__arrow-btn-wrapper {
  position: relative;
}

.overlay-editor__add-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 13px;
  background-color: white;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  font-size: 12px;
  font-weight: 500;
  color: #4a5565;
  cursor: pointer;
  transition: all 0.15s ease;
}

.overlay-editor__add-btn:hover {
  border-color: #2c3e50;
  color: #2c3e50;
}

.overlay-editor__add-btn--active {
  background-color: #2c3e50;
  border-color: #2c3e50;
  color: white;
}

.overlay-editor__add-btn--active:hover {
  background-color: #1a252f;
  border-color: #1a252f;
  color: white;
}

.overlay-editor__marker-dot {
  width: 10px;
  height: 10px;
  background-color: #ff6467;
  border-radius: 50%;
}

.overlay-editor__add-btn--active .overlay-editor__marker-dot {
  background-color: white;
}

.overlay-editor__toolbar-container {
  display: flex;
  justify-content: center;
}

.overlay-editor__arrow-picker {
  position: absolute;
  top: calc(100% + 8px);
  left: 0;
  background-color: white;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
  padding: 12px;
  z-index: 100;
  min-width: 200px;
}

.overlay-editor__arrow-picker-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
  padding-bottom: 8px;
  border-bottom: 1px solid #e5e7eb;
}

.overlay-editor__arrow-picker-title {
  font-size: 13px;
  font-weight: 600;
  color: #101828;
}

.overlay-editor__arrow-picker-close {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  background: none;
  border: none;
  border-radius: 4px;
  color: #99a1af;
  cursor: pointer;
  transition: all 0.15s ease;
}

.overlay-editor__arrow-picker-close:hover {
  background-color: #f3f4f6;
  color: #4a5565;
}

.overlay-editor__arrow-picker-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 6px;
}

.overlay-editor__arrow-picker-option {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 12px;
  background-color: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.15s ease;
  text-align: left;
}

.overlay-editor__arrow-picker-option:hover {
  background-color: #fef3c7;
  border-color: #fcd34d;
}

.overlay-editor__arrow-picker-icon {
  font-size: 18px;
  width: 24px;
  text-align: center;
}

.overlay-editor__arrow-picker-label {
  font-size: 12px;
  font-weight: 500;
  color: #101828;
}

.arrow-picker-enter-active,
.arrow-picker-leave-active {
  transition: all 0.2s ease;
}

.arrow-picker-enter-from,
.arrow-picker-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>

// apps/mobile/components/overlay/OverlayEditor.tsx
import React, { useState, useCallback, useMemo, useEffect } from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Svg, { Path } from 'react-native-svg';
import type { Overlay, ArrowDirection } from '@guidenav/types';
import { OverlayCanvas, type EditorMode } from './OverlayCanvas';
import { OverlayToolbar } from './OverlayToolbar';
import { LabelInputModal } from './LabelInputModal';
import { OverlayTutorial, type OverlayTutorialType } from './OverlayTutorial';

const ARROW_DIRECTIONS: { value: ArrowDirection; label: string }[] = [
  { value: 'left', label: 'Left' },
  { value: 'right', label: 'Right' },
  { value: 'up-down', label: 'Up/Down' },
  { value: 'forward-backward', label: 'Forward' },
];

function ArrowDirectionIcon({ direction, size = 18 }: { direction: ArrowDirection; size?: number }) {
  const color = '#555555';
  switch (direction) {
    case 'left':
      return (
        <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
          <Path d="M20 18C20 18 16 14 12 14C8 14 4 18 4 18" stroke={color} strokeWidth={2} strokeLinecap="round" />
          <Path d="M4 18L4 12" stroke={color} strokeWidth={2} strokeLinecap="round" />
          <Path d="M4 18L10 18" stroke={color} strokeWidth={2} strokeLinecap="round" />
        </Svg>
      );
    case 'right':
      return (
        <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
          <Path d="M4 18C4 18 8 14 12 14C16 14 20 18 20 18" stroke={color} strokeWidth={2} strokeLinecap="round" />
          <Path d="M20 18L20 12" stroke={color} strokeWidth={2} strokeLinecap="round" />
          <Path d="M20 18L14 18" stroke={color} strokeWidth={2} strokeLinecap="round" />
        </Svg>
      );
    case 'up-down':
      return (
        <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
          <Path d="M12 20V4M12 4L6 10M12 4L18 10" stroke={color} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'forward-backward':
      return (
        <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
          <Path d="M12 20V6M12 6L6 12M12 6L18 12" stroke={color} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
          <Path d="M6 20H18" stroke={color} strokeWidth={2} strokeLinecap="round" />
        </Svg>
      );
    default:
      return null;
  }
}

function generateId(): string {
  return `overlay-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

interface OverlayEditorProps {
  imageUrl: string;
  overlays: Overlay[];
  readonly?: boolean;
  userId?: string;
  onUpdateOverlays: (overlays: Overlay[]) => void;
}

export function OverlayEditor({
  imageUrl,
  overlays,
  readonly = false,
  userId = 'dev-user-placeholder',
  onUpdateOverlays,
}: OverlayEditorProps) {
  const [mode, setMode] = useState<EditorMode>('view');
  const [selectedOverlayId, setSelectedOverlayId] = useState<string | null>(null);
  const [showLabelModal, setShowLabelModal] = useState(false);
  const [editingLabelOverlayId, setEditingLabelOverlayId] = useState<string | null>(null);
  const [showArrowTypePicker, setShowArrowTypePicker] = useState(false);
  const [pendingArrowDirection, setPendingArrowDirection] = useState<ArrowDirection>('up-down');

  const [hasSeenArrowTutorial, setHasSeenArrowTutorial] = useState(true);
  const [hasSeenMarkerTutorial, setHasSeenMarkerTutorial] = useState(true);
  const [showTutorial, setShowTutorial] = useState(false);
  const [tutorialType, setTutorialType] = useState<OverlayTutorialType>('arrow');

  useEffect(() => {
    (async () => {
      const arrowKey = `overlay-tutorial-seen-arrow:${userId}`;
      const markerKey = `overlay-tutorial-seen-marker:${userId}`;
      const [arrowSeen, markerSeen] = await Promise.all([
        AsyncStorage.getItem(arrowKey),
        AsyncStorage.getItem(markerKey),
      ]);
      setHasSeenArrowTutorial(arrowSeen === 'true');
      setHasSeenMarkerTutorial(markerSeen === 'true');
    })();
  }, [userId]);

  const hasArrow = useMemo(() => overlays.some((o) => o.type === 'arrow'), [overlays]);
  const hasMarker = useMemo(() => overlays.some((o) => o.type === 'marker'), [overlays]);

  const selectedOverlay = useMemo(() => {
    if (!selectedOverlayId) return null;
    return overlays.find((o) => o.id === selectedOverlayId) ?? null;
  }, [overlays, selectedOverlayId]);

  const labelModalTitle = useMemo(() => {
    if (editingLabelOverlayId) {
      const overlay = overlays.find((o) => o.id === editingLabelOverlayId);
      return overlay?.label ? 'Edit Label' : 'Add Label';
    }
    return 'Add Label';
  }, [editingLabelOverlayId, overlays]);

  const labelModalInitialValue = useMemo(() => {
    if (editingLabelOverlayId) {
      const overlay = overlays.find((o) => o.id === editingLabelOverlayId);
      return overlay?.label ?? '';
    }
    return '';
  }, [editingLabelOverlayId, overlays]);

  const markArrowTutorialSeen = useCallback(async () => {
    const key = `overlay-tutorial-seen-arrow:${userId}`;
    await AsyncStorage.setItem(key, 'true');
    setHasSeenArrowTutorial(true);
  }, [userId]);

  const markMarkerTutorialSeen = useCallback(async () => {
    const key = `overlay-tutorial-seen-marker:${userId}`;
    await AsyncStorage.setItem(key, 'true');
    setHasSeenMarkerTutorial(true);
  }, [userId]);

  const handleAddArrowClick = useCallback(() => {
    if (readonly) return;
    if (mode === 'add-arrow') {
      setMode('view');
      setShowArrowTypePicker(false);
      return;
    }
    setShowArrowTypePicker(true);
    setSelectedOverlayId(null);
  }, [readonly, mode]);

  const handleArrowTypeSelect = useCallback((direction: ArrowDirection) => {
    setPendingArrowDirection(direction);
    setShowArrowTypePicker(false);
    setMode('add-arrow');
  }, []);

  const handleArrowTypePickerCancel = useCallback(() => {
    setShowArrowTypePicker(false);
  }, []);

  const handleAddMarkerClick = useCallback(() => {
    if (readonly) return;
    setMode((prev) => (prev === 'add-marker' ? 'view' : 'add-marker'));
    setSelectedOverlayId(null);
  }, [readonly]);

  const handleSelectOverlay = useCallback(
    (id: string | null) => {
      setSelectedOverlayId(id);
      if (id) {
        setMode('select');
      } else if (mode === 'select') {
        setMode('view');
      }
    },
    [mode],
  );

  const handleAddOverlay = useCallback(
    (x: number, y: number) => {
      if (mode === 'add-arrow') {
        const newOverlay: Overlay = {
          id: generateId(),
          type: 'arrow',
          x,
          y,
          scale: 2,
          rotation: 0,
          label: null,
          arrowDirection: pendingArrowDirection,
        };
        const filteredOverlays = overlays.filter((o) => o.type !== 'arrow');
        onUpdateOverlays([...filteredOverlays, newOverlay]);
        setSelectedOverlayId(newOverlay.id);
        setMode('select');

        if (!hasSeenArrowTutorial) {
          setTutorialType('arrow');
          setShowTutorial(true);
        }
      }
    },
    [mode, pendingArrowDirection, overlays, onUpdateOverlays, hasSeenArrowTutorial],
  );

  const handleCanvasTap = useCallback(
    (x: number, y: number) => {
      if (mode === 'add-marker') {
        const newOverlay: Overlay = {
          id: generateId(),
          type: 'marker',
          x,
          y,
          scale: 1,
          rotation: 0,
          label: null,
        };
        const filteredOverlays = overlays.filter((o) => o.type !== 'marker');
        onUpdateOverlays([...filteredOverlays, newOverlay]);
        setSelectedOverlayId(newOverlay.id);
        setMode('select');

        if (!hasSeenMarkerTutorial) {
          setTutorialType('marker');
          setShowTutorial(true);
        }
      }
    },
    [mode, overlays, onUpdateOverlays, hasSeenMarkerTutorial],
  );

  const handleUpdateOverlay = useCallback(
    (id: string, updates: Partial<Overlay>) => {
      const updatedOverlays = overlays.map((o) =>
        o.id === id ? { ...o, ...updates } : o,
      );
      onUpdateOverlays(updatedOverlays);
    },
    [overlays, onUpdateOverlays],
  );

  const handleChangeDirection = useCallback(
    (direction: ArrowDirection) => {
      if (!selectedOverlayId) return;
      const overlay = overlays.find((o) => o.id === selectedOverlayId);
      if (overlay && overlay.type === 'arrow') {
        handleUpdateOverlay(selectedOverlayId, { arrowDirection: direction });
      }
    },
    [selectedOverlayId, overlays, handleUpdateOverlay],
  );

  const handleEditLabel = useCallback(() => {
    if (!selectedOverlayId) return;
    setEditingLabelOverlayId(selectedOverlayId);
    setShowLabelModal(true);
  }, [selectedOverlayId]);

  const handleDelete = useCallback(() => {
    if (!selectedOverlayId) return;
    const updatedOverlays = overlays.filter((o) => o.id !== selectedOverlayId);
    onUpdateOverlays(updatedOverlays);
    setSelectedOverlayId(null);
    setMode('view');
  }, [selectedOverlayId, overlays, onUpdateOverlays]);

  const handleDone = useCallback(() => {
    setSelectedOverlayId(null);
    setMode('view');
  }, []);

  const handleLabelSave = useCallback(
    (label: string) => {
      if (editingLabelOverlayId) {
        const updatedOverlays = overlays.map((o) =>
          o.id === editingLabelOverlayId ? { ...o, label } : o,
        );
        onUpdateOverlays(updatedOverlays);
        setEditingLabelOverlayId(null);
      }
      setShowLabelModal(false);
    },
    [editingLabelOverlayId, overlays, onUpdateOverlays],
  );

  const handleLabelCancel = useCallback(() => {
    setEditingLabelOverlayId(null);
    setShowLabelModal(false);
  }, []);

  const handleTutorialComplete = useCallback(() => {
    if (tutorialType === 'arrow') {
      markArrowTutorialSeen();
    } else {
      markMarkerTutorialSeen();
    }
    setShowTutorial(false);
  }, [tutorialType, markArrowTutorialSeen, markMarkerTutorialSeen]);

  const handleTutorialSkip = useCallback(() => {
    if (tutorialType === 'arrow') {
      markArrowTutorialSeen();
    } else {
      markMarkerTutorialSeen();
    }
    setShowTutorial(false);
  }, [tutorialType, markArrowTutorialSeen, markMarkerTutorialSeen]);

  return (
    <View style={styles.editor}>
      <OverlayCanvas
        imageUrl={imageUrl}
        overlays={overlays}
        selectedId={selectedOverlayId}
        mode={mode}
        onSelectOverlay={handleSelectOverlay}
        onAddOverlay={handleAddOverlay}
        onUpdateOverlay={handleUpdateOverlay}
        onCanvasTap={handleCanvasTap}
      />

      {!readonly && (
        <View style={styles.controls}>
          <View style={styles.addButtons}>
            <Text style={styles.label}>Overlay:</Text>

            <View style={styles.arrowBtnWrapper}>
              <Pressable
                style={[
                  styles.addBtn,
                  (mode === 'add-arrow' || showArrowTypePicker) &&
                    styles.addBtnActive,
                ]}
                onPress={handleAddArrowClick}
              >
                <Svg width={12} height={12} viewBox="0 0 24 24" fill="none">
                  <Path
                    d="M7 17L17 7M17 7H7M17 7V17"
                    stroke={
                      mode === 'add-arrow' || showArrowTypePicker
                        ? 'white'
                        : '#4a5565'
                    }
                    strokeWidth={2}
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </Svg>
                <Text
                  style={[
                    styles.addBtnText,
                    (mode === 'add-arrow' || showArrowTypePicker) &&
                      styles.addBtnTextActive,
                  ]}
                >
                  {hasArrow ? 'Replace Arrow' : 'Add Arrow'}
                </Text>
              </Pressable>

              {showArrowTypePicker && (
                <View style={styles.arrowPicker}>
                  <View style={styles.arrowPickerHeader}>
                    <Text style={styles.arrowPickerTitle}>
                      Choose arrow type
                    </Text>
                    <Pressable
                      style={styles.arrowPickerClose}
                      onPress={handleArrowTypePickerCancel}
                    >
                      <Svg
                        width={16}
                        height={16}
                        viewBox="0 0 24 24"
                        fill="none"
                      >
                        <Path
                          d="M18 6L6 18M6 6L18 18"
                          stroke="#99a1af"
                          strokeWidth={2}
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </Svg>
                    </Pressable>
                  </View>
                  <View style={styles.arrowPickerGrid}>
                    {ARROW_DIRECTIONS.map((dir) => (
                      <Pressable
                        key={dir.value}
                        style={styles.arrowPickerOption}
                        onPress={() => handleArrowTypeSelect(dir.value)}
                      >
                        <ArrowDirectionIcon direction={dir.value} size={18} />
                        <Text style={styles.arrowPickerLabel} numberOfLines={1}>{dir.label}</Text>
                      </Pressable>
                    ))}
                  </View>
                </View>
              )}
            </View>

            <Pressable
              style={[
                styles.addBtn,
                mode === 'add-marker' && styles.addBtnActive,
              ]}
              onPress={handleAddMarkerClick}
            >
              <View
                style={[
                  styles.markerDot,
                  mode === 'add-marker' && styles.markerDotActive,
                ]}
              />
              <Text
                style={[
                  styles.addBtnText,
                  mode === 'add-marker' && styles.addBtnTextActive,
                ]}
              >
                {hasMarker ? 'Replace Marker' : 'Add Marker'}
              </Text>
            </Pressable>
          </View>

          {selectedOverlay && (
            <View style={styles.toolbarContainer}>
              <OverlayToolbar
                overlayType={selectedOverlay.type}
                arrowDirection={selectedOverlay.arrowDirection}
                hasLabel={!!selectedOverlay.label}
                visible={true}
                onChangeDirection={handleChangeDirection}
                onEditLabel={handleEditLabel}
                onDelete={handleDelete}
                onDone={handleDone}
              />
            </View>
          )}
        </View>
      )}

      <LabelInputModal
        visible={showLabelModal}
        initialValue={labelModalInitialValue}
        title={labelModalTitle}
        onSave={handleLabelSave}
        onCancel={handleLabelCancel}
      />

      <OverlayTutorial
        visible={showTutorial}
        type={tutorialType}
        onComplete={handleTutorialComplete}
        onSkip={handleTutorialSkip}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  editor: {
    gap: 12,
  },
  controls: {
    gap: 12,
  },
  addButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  label: {
    fontSize: 12,
    color: '#99a1af',
  },
  arrowBtnWrapper: {
    position: 'relative',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 13,
    paddingVertical: 8,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
  },
  addBtnActive: {
    backgroundColor: '#2c3e50',
    borderColor: '#2c3e50',
  },
  addBtnText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#4a5565',
  },
  addBtnTextActive: {
    color: 'white',
  },
  markerDot: {
    width: 10,
    height: 10,
    backgroundColor: '#ff6467',
    borderRadius: 5,
  },
  markerDotActive: {
    backgroundColor: 'white',
  },
  toolbarContainer: {
    alignItems: 'center',
  },
  arrowPicker: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: 8,
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 12,
    width: 240,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 100,
  },
  arrowPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  arrowPickerTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#101828',
  },
  arrowPickerClose: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  arrowPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  arrowPickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    width: '48%',
  },
  arrowPickerLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#101828',
  },
});
